version: 0.2
phases: 
  install:
    runtime_versions:
      python: 3.7
  build: 
    commands:
      - echo build started at 'date'
      - echo compiling the python code...
      - pip install requests -t .
    post_build:
      commands:
        - echo build complete on 'date'
        - pwd
        - ls-al
artifacts:
  files:
    - '**/*'
